// src/lib/storage/userIdentity.ts - Shared utility for generating deterministic user IDs

/**
 * Generate a deterministic user ID based on user credentials.
 * 
 * This function creates a consistent, secure identifier for a user based on their email
 * and password. The same credentials will always generate the same user ID, enabling:
 * - User-scoped storage without requiring a database
 * - Automatic session and settings association
 * - Privacy-preserving identification (credentials are hashed, never stored)
 * 
 * @param userEmail - User's email address (will be normalized: lowercase, trimmed)
 * @param userPassword - User's password (used as-is for hashing)
 * @returns Promise resolving to a deterministic user ID in format `user_${hash32}`
 * 
 * @example
 * const userId = await generateUserId('user@example.com', 'password123');
 * // Returns: 'user_a1b2c3d4e5f6...' (always the same for these credentials)
 */
export async function generateUserId(userEmail: string, userPassword: string): Promise<string> {
	// Create a consistent input string by normalizing the email
	const input = `${userEmail.toLowerCase().trim()}:${userPassword}`;

	// Use Web Crypto API to generate a secure hash
	const encoder = new TextEncoder();
	const data = encoder.encode(input);
	const hashBuffer = await crypto.subtle.digest('SHA-256', data);

	// Convert to hex string
	const hashArray = Array.from(new Uint8Array(hashBuffer));
	const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

	// Return a shorter, more manageable ID (first 32 characters of hash)
	return `user_${hashHex.substring(0, 32)}`;
}

/**
 * Generate a storage key for user-specific settings.
 * 
 * Creates a consistent key format for storing and retrieving user settings in KV storage.
 * This ensures settings are properly namespaced and associated with the correct user.
 * 
 * @param userId - The deterministic user ID (generated by `generateUserId`)
 * @returns A namespaced storage key in format `settings:${userId}`
 * 
 * @example
 * const userId = await generateUserId('user@example.com', 'password123');
 * const settingsKey = generateUserSettingsKey(userId);
 * // Returns: 'settings:user_a1b2c3d4e5f6...'
 */
export function generateUserSettingsKey(userId: string): string {
	return `settings:${userId}`;
}
